FROM httpd
WORKDIR /lab/httpdfile
#ADD . /go/src/nitin
#RUN go install nitin
#CMD [""]



#create httpd google_container_cluster
#Search httpd docker image on docker registry.
#- What is docker registry and register yourself.
#
