FROM httpd
WORKDIR /usr/local/apache2/htdocs/
ADD . /usr/local/apache2/htdocs/
#RUN go install nitin
#CMD [""]



#create httpd google_container_cluster
#Search httpd docker image on docker registry.
#- What is docker registry and register yourself.
#
